spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/servicematch}
    username: ${DB_USERNAME:servicematch}
    password: ${DB_PASSWORD:servicematch}
  flyway:
    enabled: true
    baseline-on-migrate: true

management:
  endpoint:
    health:
      show-details: always
