spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: ${TEST_DB_URL:jdbc:postgresql://localhost:5432/servicematch_test}
    username: ${TEST_DB_USERNAME:servicematch}
    password: ${TEST_DB_PASSWORD:servicematch}
  flyway:
    enabled: true
    baseline-on-migrate: true

management:
  endpoint:
    health:
      show-details: never
